server:
  port: 8090
spring:
  application:
    name: zipkinclient
  #设置开启请求跟踪
  sleuth:
    web:
      client:
        enabled: true
    #设置采样比例,默认1.0
    sampler:
      probability: 1.0
  #Zipkin Server 地址
  zipkin:
    base-url: http://localhost:9090/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
